name: Netlify Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      build-dir:
        required: true
        type: string
      site-id:
        required: true
        type: string
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          echo "Deploying to Netlify site: ${{ inputs.site-id }}"
          netlify deploy --prod --dir=${{ inputs.build-dir }} --site=${{ inputs.site-id }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
